sudo: required
language: python
services:
- docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
      - libsecp256k1-0
matrix:
  include:
  - os: linux
    python: "3.4"
  - if: NOT tag =~ .+
    os: linux
    python: "3.6"
  allow_failures:
  - os: linux
    python: "3.5"
  - if: tag =~ .+
    os: osx
    language: ruby
    osx_image: xcode7.3
before_install:
- source contrib/dash/travis/electrum_dash_version_env.sh
- echo electrum-pion version is $DASH_ELECTRUM_VERSION and TRAVIS_TAG is $TRAVIS_TAG
- mkdir -p build && cp contrib/dash/travis/* ./build/
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/before_install-osx.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
      ./build/before_install-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
      ./build/before_install-linux-apk.sh;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install tox; pip install tox-travis;
  fi
script:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]];then
      echo "Testing not set up yet."
      # tox;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/travis-build-osx.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
      ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
      ./build/travis-build-linux-apk.sh;
  fi
deploy:
- provider: releases
  api_key:
    secure: irLpxbWGI93WgC01M/aIz9cJlQ9AQOchCY70uusRN9y0G4bANeLoLsAung9/o1KDWf9Ewrwj5+DY49lSx9SXfypv8vG5oYkyrFN62L/OLLIo8+PI89dUWGW1HI92/8kNejfTMuLlC2QN6Ord5sOWNteVt/lvCZ1vYXinZ3mgvOrdzExs4Hi8mA+IoqTgQkM0BrCi6wx5GOI2udQDl7pzyZK05atrDmwUY+7qvND2o605sKl9UoOqocH78qZ5hmJznGTtX2lp8k9q1+9wDUDhiZeGGLaVArXWhx4PWjcR0U27wyKBajUVgxGcJPrVOnURjhrfmjtJPwWDOLpAeOTBdB78pVpggeERpG+YQvXFYAXnkglRQ3tPBFTx0I+nD17jA65dYjHyd62/6EeFBhb2Adv+9aBz1Zznwu0ovIyQEkMeK3bxl09P872Oge/AFvGV2hEncjN3XJfrieDNaltb78zKdh971rXx+xeOSjXv/opoxYOwScHM55qjZq3DKvNV0dQWs0b/+AZ6SNkceAWmNbCMm9exHcURgtERRtLMrKhhsf0kR9Idvq34yEuo1qRNjThtBQ0TF1Bd58pyVBNDqj8RjDA2kCxWpaQptTo7xzrP8fRxSJRQjmcZk/YGNOWKtGR8Xfn0Gxh6u38klpfqy1hdr0nFyThPJf138Z9INPg=
  file:
  - build/electrum-pion/dist/Pion-Electrum-$DASH_ELECTRUM_VERSION-macosx.dmg
  on:
    repo: pioncoin/electrum-pion
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  api_key:
    secure: irLpxbWGI93WgC01M/aIz9cJlQ9AQOchCY70uusRN9y0G4bANeLoLsAung9/o1KDWf9Ewrwj5+DY49lSx9SXfypv8vG5oYkyrFN62L/OLLIo8+PI89dUWGW1HI92/8kNejfTMuLlC2QN6Ord5sOWNteVt/lvCZ1vYXinZ3mgvOrdzExs4Hi8mA+IoqTgQkM0BrCi6wx5GOI2udQDl7pzyZK05atrDmwUY+7qvND2o605sKl9UoOqocH78qZ5hmJznGTtX2lp8k9q1+9wDUDhiZeGGLaVArXWhx4PWjcR0U27wyKBajUVgxGcJPrVOnURjhrfmjtJPwWDOLpAeOTBdB78pVpggeERpG+YQvXFYAXnkglRQ3tPBFTx0I+nD17jA65dYjHyd62/6EeFBhb2Adv+9aBz1Zznwu0ovIyQEkMeK3bxl09P872Oge/AFvGV2hEncjN3XJfrieDNaltb78zKdh971rXx+xeOSjXv/opoxYOwScHM55qjZq3DKvNV0dQWs0b/+AZ6SNkceAWmNbCMm9exHcURgtERRtLMrKhhsf0kR9Idvq34yEuo1qRNjThtBQ0TF1Bd58pyVBNDqj8RjDA2kCxWpaQptTo7xzrP8fRxSJRQjmcZk/YGNOWKtGR8Xfn0Gxh6u38klpfqy1hdr0nFyThPJf138Z9INPg=
  file:
  - build/electrum-pion/dist/Pion-Electrum-$DASH_ELECTRUM_VERSION.tar.gz
  - build/electrum-pion/dist/Pion-Electrum-$DASH_ELECTRUM_VERSION-setup-win32.exe
  - build/electrum-pion/dist/Pion-Electrum-$DASH_ELECTRUM_VERSION-setup-win64.exe
  - build/electrum-pion/bin/Electrum_DASH-$DASH_ELECTRUM_APK_VERSION-release-unsigned.apk
  on:
    repo: pioncoin/electrum-pion
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
notifications:
  slack:
    secure: g2tFyXklhL4WOD/jQ8nxiOBqVv2F26iE4aVgvpclQ/9Fnh6jXEk3jCXyMqt39fcbB4Hka2wPr4n5uWH3tRaChFpwK5LQS5vuymllloqdxAShgIXXciZ1k/Ka1K+mxMEPJriQm4MT5AvzcLVSkJ0i5LYW8nWgG7+fTEullWS4hlPLC77C36iK2CWDaxfFqqe8oPTdsCVbik8HQ62ZWDM6Sh6TZbQD7F9eUBmiwwQhRB2BMxPkWghwQ//FRJ+PIpg7PtWRru/JjNg3adOsHnwlltqUVAolacZCbpxDKFR+GLpYmLkMrwdnVA7apZ2In/yo25ByAkxshCgw45lmGB0dtC1zeAe3Get9eGP5w3o9Zedj5T5esX0BNArDK70C+kTXcPeJaRRQJPrs5OYXRPKjD+uiJqe1fIFSmhdM6vvuMPdyA1z0Fd0/9G2O/Qi8tFxcFmM8n6JQGfD9ojOQF8fPYcHM9gsOgNU9J2PfV3RnRtv3VZogxs4azKG2M8JhD/lwqZBNi4FgdllW6NE7+5TB2KX07xy/zx0m81u8k6J228sAuiRsUBcpmW7pqlqLIENMzwV8pDcA93Ps0EWJKWbzRi+hIEkBnaFE9WHY0GcKuW0TCrnonZ4FOnJNO/G9HzxvQ97bcJDvhUloJ2pBBsH0P4IZ1RlDXFpc5DqTT2qxZSo=
